version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ebuyseller-app
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:Tjjy4TfdarBd26GuhQPxo/HuDrivbxeflY/tUbBNj50=
      DB_CONNECTION: mysql
      DB_HOST: sql12.freesqldatabase.com
      DB_PORT: 3306
      DB_DATABASE: sql12808756
      DB_USERNAME: sql12808756
      DB_PASSWORD: Es2dENsz9p
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120
      MAIL_MAILER: smtp
      MAIL_HOST: smtp.mailtrap.io
      MAIL_PORT: 2525
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: null
      MAIL_FROM_NAME: eBuySeller
      PUSHER_APP_ID: ''
      PUSHER_APP_KEY: ''
      PUSHER_APP_SECRET: ''
      PUSHER_APP_CLUSTER: mt1
    ports:
      - "8000:80"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
