services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ebuyseller-app
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:Tjjy4TfdarBd26GuhQPxo/HuDrivbxeflY/tUbBNj50=
      DB_CONNECTION: mysql
      DB_HOST: sql12.freesqldatabase.com
      DB_PORT: 3306
      DB_DATABASE: sql12808756
      DB_USERNAME: sql12808756
      DB_PASSWORD: Es2dENsz9p
    ports:
      - "8080:80"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
